//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Exceptions {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessageException {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessageException() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CRM.Exceptions.ResourceMessageException", typeof(ResourceMessageException).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Account type is required.
        /// </summary>
        public static string ACCOUNT_TYPE_EMPTY {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user type must be &apos;individual&apos;, &apos;agent&apos;, or &apos;agency.
        /// </summary>
        public static string ACCOUNT_TYPE_INVALID {
            get {
                return ResourceManager.GetString("ACCOUNT_TYPE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a AgentI cannot be empty.
        /// </summary>
        public static string AGENT_EMPTY {
            get {
                return ResourceManager.GetString("AGENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Amount paid cannot be negative..
        /// </summary>
        public static string AMOUNT_PAID_NEGATIVE {
            get {
                return ResourceManager.GetString("AMOUNT_PAID_NEGATIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Billing cycle is invalid..
        /// </summary>
        public static string BILLING_CYCLE_INVALID {
            get {
                return ResourceManager.GetString("BILLING_CYCLE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a City cannot be empty.
        /// </summary>
        public static string CITY_EMPTY {
            get {
                return ResourceManager.GetString("CITY_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Client alredy exists with this document.
        /// </summary>
        public static string CLIENT_ALREDY_EXISTS {
            get {
                return ResourceManager.GetString("CLIENT_ALREDY_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ClientId cannot be empty.
        /// </summary>
        public static string CLIENT_ID_EMPTY {
            get {
                return ResourceManager.GetString("CLIENT_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Client not found.
        /// </summary>
        public static string CLIENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("CLIENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid client type.
        /// </summary>
        public static string CLIENT_TYPE_EMPTY {
            get {
                return ResourceManager.GetString("CLIENT_TYPE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The passwords do not match..
        /// </summary>
        public static string CONFIRM_PASSWORD_MATCH {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD_MATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Confirm password is required.
        /// </summary>
        public static string CONFIRM_PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("CONFIRM_PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Document cannot be empty.
        /// </summary>
        public static string DOCUMENT_EMPTY {
            get {
                return ResourceManager.GetString("DOCUMENT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail alredy registered.
        /// </summary>
        public static string EMAIL_ALREDY_REGISTERED {
            get {
                return ResourceManager.GetString("EMAIL_ALREDY_REGISTERED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The e-mail cannot be empty.
        /// </summary>
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The e-mail address invalid.
        /// </summary>
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a E-mail or password invalid.
        /// </summary>
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a End date must be after the start date..
        /// </summary>
        public static string END_DATE_AFTER_START_DATE {
            get {
                return ResourceManager.GetString("END_DATE_AFTER_START_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a End date is required..
        /// </summary>
        public static string END_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("END_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The gender cannot be empty.
        /// </summary>
        public static string GENDER_EMPTY {
            get {
                return ResourceManager.GetString("GENDER_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid gender.
        /// </summary>
        public static string GENDER_INVALID {
            get {
                return ResourceManager.GetString("GENDER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inactive plan.
        /// </summary>
        public static string INACTIVE_PLAN {
            get {
                return ResourceManager.GetString("INACTIVE_PLAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid password.
        /// </summary>
        public static string INVALID_PASSWORD {
            get {
                return ResourceManager.GetString("INVALID_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid organization.
        /// </summary>
        public static string INVALID_TENANT {
            get {
                return ResourceManager.GetString("INVALID_TENANT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invalid or inactive organization.
        /// </summary>
        public static string INVALID_TENANT_OR_INACTIVE {
            get {
                return ResourceManager.GetString("INVALID_TENANT_OR_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Invoice URL must be at most 255 characters long..
        /// </summary>
        public static string INVOICE_URL_MAX_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("INVOICE_URL_MAX_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Link empty.
        /// </summary>
        public static string LINK_INVALID {
            get {
                return ResourceManager.GetString("LINK_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The name cannot be empty.
        /// </summary>
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The name cannot have fewer than 3 characters and cannot have more than 50..
        /// </summary>
        public static string NAME_LENGTH {
            get {
                return ResourceManager.GetString("NAME_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Neighborhood cannot be empty.
        /// </summary>
        public static string NEIGHBORHOO_EMPTY {
            get {
                return ResourceManager.GetString("NEIGHBORHOO_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Neighborhood cannot be empty.
        /// </summary>
        public static string NEIGHBORHOOD {
            get {
                return ResourceManager.GetString("NEIGHBORHOOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a No access token.
        /// </summary>
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password different of current password.
        /// </summary>
        public static string PASSWORD_DIFFERENT_CURRENT_PASSWORD {
            get {
                return ResourceManager.GetString("PASSWORD_DIFFERENT_CURRENT_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Password empty.
        /// </summary>
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must be at least 6 characters long..
        /// </summary>
        public static string PASSWORD_LENGTH {
            get {
                return ResourceManager.GetString("PASSWORD_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password is required.
        /// </summary>
        public static string PASSWORD_REQUIRED {
            get {
                return ResourceManager.GetString("PASSWORD_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must contain at least one uppercase letter..
        /// </summary>
        public static string PASSWORD_RULE_1 {
            get {
                return ResourceManager.GetString("PASSWORD_RULE_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must contain at least one lowercase letter..
        /// </summary>
        public static string PASSWORD_RULE_2 {
            get {
                return ResourceManager.GetString("PASSWORD_RULE_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The password must contain at least one number..
        /// </summary>
        public static string PASSWORD_RULE_3 {
            get {
                return ResourceManager.GetString("PASSWORD_RULE_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Payment method is invalid..
        /// </summary>
        public static string PAYMENT_METHOD_INVALID {
            get {
                return ResourceManager.GetString("PAYMENT_METHOD_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Payment status is invalid..
        /// </summary>
        public static string PAYMENT_STATUS_INVALID {
            get {
                return ResourceManager.GetString("PAYMENT_STATUS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The phone number cannot be empty.
        /// </summary>
        public static string PHONE_EMPTY {
            get {
                return ResourceManager.GetString("PHONE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Phone invalid.
        /// </summary>
        public static string PHONE_INVALID {
            get {
                return ResourceManager.GetString("PHONE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The number cannot have more than 14 digits..
        /// </summary>
        public static string PHONE_MAX_LENTH {
            get {
                return ResourceManager.GetString("PHONE_MAX_LENTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The selected plan is required.
        /// </summary>
        public static string PLAN_ID_EMPTY {
            get {
                return ResourceManager.GetString("PLAN_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plan not found or inative.
        /// </summary>
        public static string PLAN_NOT_FOUND_OR_INACTIVE {
            get {
                return ResourceManager.GetString("PLAN_NOT_FOUND_OR_INACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Plan status is invalid..
        /// </summary>
        public static string PLAN_STATUS_INVALID {
            get {
                return ResourceManager.GetString("PLAN_STATUS_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Platform cannot be empty.
        /// </summary>
        public static string PLATFORM_EMPTY {
            get {
                return ResourceManager.GetString("PLATFORM_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Price must be greater than zero.
        /// </summary>
        public static string PRICE_INVALID {
            get {
                return ResourceManager.GetString("PRICE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PropertyId cannot be empty.
        /// </summary>
        public static string PROPERTY_ID_EMPTY {
            get {
                return ResourceManager.GetString("PROPERTY_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Purpose cannot be empty.
        /// </summary>
        public static string PROPERTY_PURPOSE_EMPTY {
            get {
                return ResourceManager.GetString("PROPERTY_PURPOSE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status cannot be empty.
        /// </summary>
        public static string PROPERTY_STATUS_EMPTY {
            get {
                return ResourceManager.GetString("PROPERTY_STATUS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Property type cannot be empty.
        /// </summary>
        public static string PROPERTY_TYPE_EMPTY {
            get {
                return ResourceManager.GetString("PROPERTY_TYPE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The role must be one of the following: &apos;owner&apos;, &apos;admin&apos;, &apos;manager&apos;, &apos;agent&apos;, &apos;client&apos;, &apos;financial&apos;, or &apos;assistant&apos;..
        /// </summary>
        public static string ROLE_MUST_BE {
            get {
                return ResourceManager.GetString("ROLE_MUST_BE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The role is required.
        /// </summary>
        public static string ROLE_REQUIRED {
            get {
                return ResourceManager.GetString("ROLE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start date is required..
        /// </summary>
        public static string START_DATE_REQUIRED {
            get {
                return ResourceManager.GetString("START_DATE_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a State cannot be empty.
        /// </summary>
        public static string STATE_EMPTY {
            get {
                return ResourceManager.GetString("STATE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status cannot be empty.
        /// </summary>
        public static string STATUS_EMPTY {
            get {
                return ResourceManager.GetString("STATUS_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Street cannot be empty.
        /// </summary>
        public static string STREET_EMPTY {
            get {
                return ResourceManager.GetString("STREET_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The user needs to be associated with a tenant..
        /// </summary>
        public static string TENANT_REQUIRED {
            get {
                return ResourceManager.GetString("TENANT_REQUIRED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Unknow error.
        /// </summary>
        public static string UNKNOW_ERROR {
            get {
                return ResourceManager.GetString("UNKNOW_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User not found or disabled..
        /// </summary>
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a User without permission to access this resource.
        /// </summary>
        public static string USER_WITHOUT_PERMISSION_ACCESS_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION_ACCESS_RESOURCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a ZipCode cannot be empty.
        /// </summary>
        public static string ZIPCODE_EMPTY {
            get {
                return ResourceManager.GetString("ZIPCODE_EMPTY", resourceCulture);
            }
        }
    }
}
